#!/bin/bash
#PBS -N /home/goodpast/graha682/code/python/QSoME/qsome/run_embeddin
#PBS -l nodes=1:ppn=24
#PBS -l walltime=72:00:00
#PBS -l pmem=2500mb
#PBS -e /home/goodpast/graha682/code/python/QSoME/qsome/run_embedding.err
#PBS -o /home/goodpast/graha682/code/python/QSoME/qsome/run_embedding.log
#PBS -q mesabi

module load python
module load molpro/2019.2

# create scratch directory
scratch=/scratch.global/graha682//home/goodpast/graha682/code/python/QSoME/qsome/run_embedding
if [[ -d $scratch ]]; then
    i=0
    while [[ -d $scratch-$i ]]; do
        let i++
    done
    scratch=$scratch-$i
fi
rm -rf $scratch 2> /dev/null
mkdir -p $scratch
cd $scratch

export HDF5_USE_FILE_LOCKING=FALSE
python  /home/goodpast/graha682/code/python/QSoME/qsome/run_embedding.py > /home/goodpast/graha682/code/python/QSoME/qsome/run_embedding.out

cd ${PBS_O_WORKDIR}
rm -rf $scratch 2> /dev/null
